import { mutation } from "./_generated/server";

type ProviderMeta = {
  category: string;
  serviceKinds: string[];
  iconUrl?: string;
  website?: string;
  hasFree?: boolean;
};

const PROVIDER_META: Record<string, ProviderMeta> = {
  "360ai": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "9router": { category: "proxy", serviceKinds: ["llm"] },
  "adapta-web": { category: "cookie", serviceKinds: ["llm"], website: "https://adapta.org" },
  "agentrouter": { category: "aggregator", serviceKinds: ["llm"], hasFree: true },
  "ai21": { category: "apikey", serviceKinds: ["llm"], website: "https://studio.ai21.com", hasFree: true },
  "aimlapi": { category: "aggregator", serviceKinds: ["llm", "image"], website: "https://aimlapi.com", hasFree: true },
  "alibaba": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/alibabadotcom", website: "https://dashscope.aliyun.com" },
  "alibaba-cn": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/alibabadotcom", website: "https://dashscope.aliyun.com" },
  "alibaba-coding": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/alibabadotcom", website: "https://dashscope.aliyun.com" },
  "amazon-q": { category: "oauth", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/amazonwebservices", website: "https://aws.amazon.com/q/", hasFree: true },
  "anthropic": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/anthropic", website: "https://console.anthropic.com" },
  "antigravity": { category: "oauth", serviceKinds: ["llm"] },
  "antigravity-cli": { category: "oauth", serviceKinds: ["llm"], hasFree: true },
  "api-airforce": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "arcee-ai": { category: "apikey", serviceKinds: ["llm"], website: "https://arcee.ai", hasFree: true },
  "assemblyai": { category: "audio", serviceKinds: ["stt"], website: "https://assemblyai.com" },
  "aws-polly": { category: "audio", serviceKinds: ["tts"], iconUrl: "https://cdn.simpleicons.org/amazonwebservices", website: "https://aws.amazon.com/polly/" },
  "azure-ai": { category: "enterprise", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/microsoftazure", website: "https://ai.azure.com" },
  "azure-openai": { category: "enterprise", serviceKinds: ["llm", "embedding"], iconUrl: "https://cdn.simpleicons.org/microsoftazure", website: "https://azure.microsoft.com/products/ai-services/openai-service" },
  "baichuan": { category: "apikey", serviceKinds: ["llm"], website: "https://www.baichuan-ai.com", hasFree: true },
  "baidu": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/baidu", website: "https://cloud.baidu.com", hasFree: true },
  "baseten": { category: "apikey", serviceKinds: ["llm"], website: "https://baseten.co", hasFree: true },
  "bazaarlink": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "bedrock": { category: "enterprise", serviceKinds: ["llm", "embedding"], iconUrl: "https://cdn.simpleicons.org/amazonwebservices", website: "https://aws.amazon.com/bedrock/" },
  "black-forest-labs": { category: "image", serviceKinds: ["image"], website: "https://blackforestlabs.ai" },
  "blackbox": { category: "apikey", serviceKinds: ["llm"], website: "https://blackbox.ai", hasFree: true },
  "blackbox-web": { category: "cookie", serviceKinds: ["llm"], website: "https://blackbox.ai" },
  "bluesminds": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "brave-search": { category: "search", serviceKinds: ["search"], iconUrl: "https://cdn.simpleicons.org/brave", website: "https://search.brave.com", hasFree: true },
  "byteplus": { category: "apikey", serviceKinds: ["llm"], website: "https://www.byteplus.com", hasFree: true },
  "bytez": { category: "apikey", serviceKinds: ["llm"], website: "https://bytez.com", hasFree: true },
  "cablyai": { category: "aggregator", serviceKinds: ["llm"] },
  "cartesia": { category: "audio", serviceKinds: ["tts"], website: "https://cartesia.ai" },
  "cerebras": { category: "apikey", serviceKinds: ["llm"], website: "https://cloud.cerebras.ai", hasFree: true },
  "chatgpt-web": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/openai", website: "https://chatgpt.com" },
  "chipotle": { category: "noauth", serviceKinds: ["llm"], hasFree: true },
  "chutes": { category: "aggregator", serviceKinds: ["llm"], website: "https://chutes.ai", hasFree: true },
  "clarifai": { category: "enterprise", serviceKinds: ["llm", "image"], website: "https://clarifai.com" },
  "claude-code": { category: "oauth", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/anthropic", website: "https://claude.ai/code" },
  "claude-web": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/anthropic", website: "https://claude.ai" },
  "cline": { category: "oauth", serviceKinds: ["llm"], website: "https://cline.bot" },
  "cliproxyapi": { category: "proxy", serviceKinds: ["llm"] },
  "cloudflare-ai": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/cloudflare", website: "https://developers.cloudflare.com/workers-ai/", hasFree: true },
  "codestral": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/mistral/000", website: "https://mistral.ai/news/codestral" },
  "codex-cloud": { category: "cloud_agent", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/openai", website: "https://openai.com/codex" },
  "cohere": { category: "apikey", serviceKinds: ["llm", "embedding"], iconUrl: "https://cdn.simpleicons.org/cohere", website: "https://cohere.com", hasFree: true },
  "comfyui": { category: "local", serviceKinds: ["image"], website: "https://comfyui.com", hasFree: true },
  "command-code": { category: "apikey", serviceKinds: ["llm"] },
  "copilot-web": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/microsoft", website: "https://copilot.microsoft.com" },
  "coze": { category: "apikey", serviceKinds: ["llm"], website: "https://coze.com", hasFree: true },
  "crofai": { category: "apikey", serviceKinds: ["llm"] },
  "cursor": { category: "ide", serviceKinds: ["llm"], website: "https://cursor.com" },
  "databricks": { category: "enterprise", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/databricks", website: "https://databricks.com" },
  "datarobot": { category: "enterprise", serviceKinds: ["llm"], website: "https://datarobot.com" },
  "deepgram": { category: "audio", serviceKinds: ["stt", "tts"], website: "https://deepgram.com" },
  "deepinfra": { category: "apikey", serviceKinds: ["llm", "embedding"], website: "https://deepinfra.com", hasFree: true },
  "deepseek": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/deepseek", website: "https://platform.deepseek.com", hasFree: true },
  "deepseek-web": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/deepseek", website: "https://chat.deepseek.com" },
  "devin": { category: "cloud_agent", serviceKinds: ["llm"], website: "https://devin.ai" },
  "devin-cli": { category: "oauth", serviceKinds: ["llm"], website: "https://devin.ai" },
  "dify": { category: "apikey", serviceKinds: ["llm"], website: "https://dify.ai", hasFree: true },
  "docker-model": { category: "local", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/docker", website: "https://docker.com" },
  "doubao": { category: "apikey", serviceKinds: ["llm"], website: "https://www.volcengine.com/product/doubao", hasFree: true },
  "doubao-web": { category: "cookie", serviceKinds: ["llm"], website: "https://www.doubao.com" },
  "duckduckgo": { category: "noauth", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/duckduckgo", website: "https://duckduckgo.com", hasFree: true },
  "elevenlabs": { category: "audio", serviceKinds: ["tts"], website: "https://elevenlabs.io" },
  "empower": { category: "aggregator", serviceKinds: ["llm"] },
  "exa-search": { category: "fetch", serviceKinds: ["search"], website: "https://exa.ai", hasFree: true },
  "fal-ai": { category: "image", serviceKinds: ["image", "video"], website: "https://fal.ai" },
  "featherless-ai": { category: "apikey", serviceKinds: ["llm"], website: "https://featherless.ai", hasFree: true },
  "fenayai": { category: "aggregator", serviceKinds: ["llm"] },
  "firecrawl": { category: "fetch", serviceKinds: ["search"], website: "https://firecrawl.dev", hasFree: true },
  "fireworks": { category: "apikey", serviceKinds: ["llm", "image", "embedding"], website: "https://fireworks.ai", hasFree: true },
  "freeaiapikey": { category: "apikey", serviceKinds: ["llm"] },
  "freemodel": { category: "apikey", serviceKinds: ["llm"], website: "https://freemodel.dev", hasFree: true },
  "friendliai": { category: "apikey", serviceKinds: ["llm"], website: "https://friendli.ai", hasFree: true },
  "galadriel": { category: "apikey", serviceKinds: ["llm"], website: "https://galadriel.com" },
  "gemini": { category: "apikey", serviceKinds: ["llm", "embedding"], iconUrl: "https://cdn.simpleicons.org/google", website: "https://aistudio.google.com", hasFree: true },
  "gemini-business": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/google", website: "https://gemini.google.com", hasFree: true },
  "gemini-cli": { category: "oauth", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/google", website: "https://ai.google.dev/gemini-api/docs/cli", hasFree: true },
  "gemini-web": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/google", website: "https://gemini.google.com" },
  "gigachat": { category: "apikey", serviceKinds: ["llm"] },
  "github-copilot": { category: "oauth", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/github", website: "https://github.com/features/copilot" },
  "github-models": { category: "apikey", serviceKinds: ["llm", "embedding"], iconUrl: "https://cdn.simpleicons.org/github", website: "https://github.com/marketplace/models", hasFree: true },
  "gitlab": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/gitlab", website: "https://about.gitlab.com/gitlab-duo/" },
  "gitlab-duo": { category: "oauth", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/gitlab", website: "https://about.gitlab.com/gitlab-duo/" },
  "glhf": { category: "aggregator", serviceKinds: ["llm"], website: "https://glhf.chat", hasFree: true },
  "glm": { category: "apikey", serviceKinds: ["llm"] },
  "glm-cn": { category: "apikey", serviceKinds: ["llm"] },
  "glmt": { category: "apikey", serviceKinds: ["llm"] },
  "gmi-cloud": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "gmi-mimo": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "goapi": { category: "aggregator", serviceKinds: ["llm"] },
  "google-jules": { category: "cloud_agent", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/google", website: "https://jules.google.com" },
  "google-search": { category: "search", serviceKinds: ["search"], iconUrl: "https://cdn.simpleicons.org/google", website: "https://programmablesearchengine.google.com" },
  "grok-web": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/x/000", website: "https://grok.com" },
  "groq": { category: "apikey", serviceKinds: ["llm", "stt"], iconUrl: "https://cdn.simpleicons.org/groq", website: "https://console.groq.com", hasFree: true },
  "hackclub": { category: "aggregator", serviceKinds: ["llm"], website: "https://hackclub.com", hasFree: true },
  "haiper": { category: "video", serviceKinds: ["video"], website: "https://haiper.ai" },
  "heroku": { category: "enterprise", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/heroku", website: "https://heroku.com" },
  "huggingchat": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/huggingface", website: "https://huggingface.co/chat", hasFree: true },
  "huggingface": { category: "apikey", serviceKinds: ["llm", "embedding"], iconUrl: "https://cdn.simpleicons.org/huggingface", website: "https://huggingface.co", hasFree: true },
  "hyperbolic": { category: "apikey", serviceKinds: ["llm"], website: "https://hyperbolic.xyz", hasFree: true },
  "ideogram": { category: "apikey", serviceKinds: ["image"], website: "https://ideogram.ai" },
  "iflytek": { category: "apikey", serviceKinds: ["llm"], website: "https://www.xfyun.cn", hasFree: true },
  "inclusionai": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "inference-net": { category: "apikey", serviceKinds: ["llm"], website: "https://inference.net", hasFree: true },
  "inner-ai": { category: "cookie", serviceKinds: ["llm"], website: "https://inner.ai" },
  "inworld": { category: "audio", serviceKinds: ["tts"], website: "https://inworld.ai" },
  "jina-ai": { category: "embedding", serviceKinds: ["embedding"], website: "https://jina.ai", hasFree: true },
  "jina-reader": { category: "fetch", serviceKinds: ["search"], website: "https://jina.ai/reader", hasFree: true },
  "kie": { category: "apikey", serviceKinds: ["llm"], website: "https://kie.ai" },
  "kilo-code": { category: "oauth", serviceKinds: ["llm"] },
  "kilo-gateway": { category: "aggregator", serviceKinds: ["llm"] },
  "kimi": { category: "apikey", serviceKinds: ["llm"], website: "https://platform.moonshot.cn" },
  "kimi-coding": { category: "oauth", serviceKinds: ["llm"] },
  "kimi-coding-api": { category: "apikey", serviceKinds: ["llm"] },
  "kimi-web": { category: "cookie", serviceKinds: ["llm"], website: "https://kimi.moonshot.cn" },
  "kiro": { category: "oauth", serviceKinds: ["llm"], website: "https://kiro.dev", hasFree: true },
  "kluster": { category: "apikey", serviceKinds: ["llm"], website: "https://kluster.ai", hasFree: true },
  "lambda-ai": { category: "apikey", serviceKinds: ["llm"], website: "https://lambda.ai" },
  "laozhang": { category: "aggregator", serviceKinds: ["llm"] },
  "lemonade": { category: "local", serviceKinds: ["llm"] },
  "leonardo": { category: "video", serviceKinds: ["video", "image"], website: "https://leonardo.ai" },
  "linkup-search": { category: "search", serviceKinds: ["search"] },
  "liquid": { category: "apikey", serviceKinds: ["llm"], website: "https://liquid.ai", hasFree: true },
  "llama-cpp": { category: "local", serviceKinds: ["llm"], website: "https://github.com/ggerganov/llama.cpp" },
  "llamafile": { category: "local", serviceKinds: ["llm"], website: "https://llamafile.ai" },
  "llamagate": { category: "apikey", serviceKinds: ["llm"] },
  "llm7": { category: "apikey", serviceKinds: ["llm"], website: "https://llm7.io", hasFree: true },
  "lmarena": { category: "cookie", serviceKinds: ["llm"], website: "https://lmarena.ai", hasFree: true },
  "lmstudio": { category: "local", serviceKinds: ["llm"], website: "https://lmstudio.ai" },
  "longcat": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "maritalk": { category: "apikey", serviceKinds: ["llm"] },
  "meta-llama": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/meta", website: "https://llama.meta.com" },
  "minimax": { category: "apikey", serviceKinds: ["llm", "video"], website: "https://www.minimaxi.com" },
  "minimax-cn": { category: "apikey", serviceKinds: ["llm"] },
  "minimax-video": { category: "video", serviceKinds: ["video"] },
  "mistral": { category: "apikey", serviceKinds: ["llm", "embedding"], iconUrl: "https://cdn.simpleicons.org/mistral/000", website: "https://console.mistral.ai", hasFree: true },
  "modal": { category: "enterprise", serviceKinds: ["llm"], website: "https://modal.com", hasFree: true },
  "monsterapi": { category: "apikey", serviceKinds: ["llm"], website: "https://monsterapi.ai", hasFree: true },
  "moonshot": { category: "apikey", serviceKinds: ["llm"], website: "https://platform.moonshot.cn" },
  "morph": { category: "apikey", serviceKinds: ["llm"], website: "https://morph.so", hasFree: true },
  "muse-spark": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/meta", website: "https://meta.ai", hasFree: true },
  "nanogpt": { category: "apikey", serviceKinds: ["llm"] },
  "nebius": { category: "apikey", serviceKinds: ["llm"], website: "https://nebius.ai", hasFree: true },
  "nlpcloud": { category: "apikey", serviceKinds: ["llm"], website: "https://nlpcloud.com", hasFree: true },
  "nomic": { category: "apikey", serviceKinds: ["embedding"], website: "https://nomic.ai", hasFree: true },
  "nous-research": { category: "apikey", serviceKinds: ["llm"], website: "https://nousresearch.com", hasFree: true },
  "novita": { category: "aggregator", serviceKinds: ["llm", "image"], website: "https://novita.ai", hasFree: true },
  "nscale": { category: "apikey", serviceKinds: ["llm"], website: "https://nscale.com", hasFree: true },
  "nvidia": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/nvidia", website: "https://build.nvidia.com", hasFree: true },
  "nvidia-triton": { category: "local", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/nvidia", website: "https://developer.nvidia.com/triton-inference-server" },
  "oci": { category: "enterprise", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/oracle", website: "https://cloud.oracle.com" },
  "old-llm": { category: "noauth", serviceKinds: ["llm"], hasFree: true },
  "ollama-cloud": { category: "apikey", serviceKinds: ["llm"], website: "https://ollama.com", hasFree: true },
  "ollama-search": { category: "search", serviceKinds: ["search"], website: "https://ollama.com" },
  "oobabooga": { category: "local", serviceKinds: ["llm"], website: "https://github.com/oobabooga/text-generation-webui" },
  "openai": { category: "apikey", serviceKinds: ["llm", "image", "embedding", "tts", "stt"], iconUrl: "https://cdn.simpleicons.org/openai", website: "https://platform.openai.com" },
  "openai-codex": { category: "oauth", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/openai", website: "https://openai.com/codex" },
  "opencode-free": { category: "noauth", serviceKinds: ["llm"], hasFree: true },
  "opencode-go": { category: "apikey", serviceKinds: ["llm"] },
  "opencode-zen": { category: "apikey", serviceKinds: ["llm"] },
  "openrouter": { category: "aggregator", serviceKinds: ["llm"], website: "https://openrouter.ai", hasFree: true },
  "ovhcloud": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/ovh", website: "https://ovhcloud.com" },
  "perplexity": { category: "apikey", serviceKinds: ["llm", "search"], iconUrl: "https://cdn.simpleicons.org/perplexity", website: "https://docs.perplexity.ai" },
  "perplexity-search": { category: "search", serviceKinds: ["search"], iconUrl: "https://cdn.simpleicons.org/perplexity", website: "https://perplexity.ai" },
  "perplexity-web": { category: "cookie", serviceKinds: ["llm", "search"], iconUrl: "https://cdn.simpleicons.org/perplexity", website: "https://perplexity.ai" },
  "phind": { category: "apikey", serviceKinds: ["llm", "search"], website: "https://phind.com", hasFree: true },
  "phind-web": { category: "cookie", serviceKinds: ["llm", "search"], website: "https://phind.com", hasFree: true },
  "piapi": { category: "aggregator", serviceKinds: ["llm"] },
  "playht": { category: "audio", serviceKinds: ["tts"], website: "https://play.ht" },
  "poe": { category: "aggregator", serviceKinds: ["llm"], website: "https://poe.com" },
  "poe-web": { category: "cookie", serviceKinds: ["llm"], website: "https://poe.com" },
  "pollinations": { category: "video", serviceKinds: ["image", "video"], website: "https://pollinations.ai", hasFree: true },
  "predibase": { category: "apikey", serviceKinds: ["llm"], website: "https://predibase.com", hasFree: true },
  "publicai": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "puter": { category: "apikey", serviceKinds: ["llm"], website: "https://puter.com", hasFree: true },
  "qianfan": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/baidu", website: "https://cloud.baidu.com/product/wenxinworkshop" },
  "qoder-ai": { category: "oauth", serviceKinds: ["llm"], hasFree: true },
  "qwen-code": { category: "oauth", serviceKinds: ["llm"] },
  "qwen-web": { category: "cookie", serviceKinds: ["llm"], website: "https://chat.qwen.ai", hasFree: true },
  "recraft": { category: "image", serviceKinds: ["image"], website: "https://recraft.ai" },
  "reka": { category: "apikey", serviceKinds: ["llm"], website: "https://reka.ai", hasFree: true },
  "runway": { category: "video", serviceKinds: ["video"], website: "https://runwayml.com" },
  "sambanova": { category: "apikey", serviceKinds: ["llm"], website: "https://cloud.sambanova.ai", hasFree: true },
  "sap": { category: "enterprise", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/sap", website: "https://sap.com" },
  "scaleway": { category: "apikey", serviceKinds: ["llm"], website: "https://scaleway.com", hasFree: true },
  "sd-webui": { category: "local", serviceKinds: ["image"], hasFree: true },
  "searchapi": { category: "search", serviceKinds: ["search"], website: "https://searchapi.io" },
  "searxng": { category: "search", serviceKinds: ["search"], website: "https://searxng.org", hasFree: true },
  "sensenova": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "serper": { category: "search", serviceKinds: ["search"], website: "https://serper.dev", hasFree: true },
  "siliconflow": { category: "apikey", serviceKinds: ["llm", "image", "embedding"], website: "https://siliconflow.cn", hasFree: true },
  "snowflake": { category: "enterprise", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/snowflake", website: "https://snowflake.com" },
  "sparkdesk": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "stability-ai": { category: "image", serviceKinds: ["image"], website: "https://stability.ai" },
  "stepfun": { category: "apikey", serviceKinds: ["llm"], website: "https://stepfun.com", hasFree: true },
  "suno": { category: "apikey", serviceKinds: ["audio"], website: "https://suno.com" },
  "synthetic": { category: "aggregator", serviceKinds: ["llm"] },
  "t3-chat": { category: "cookie", serviceKinds: ["llm"], website: "https://t3.chat", hasFree: true },
  "tavily": { category: "search", serviceKinds: ["search"], website: "https://tavily.com", hasFree: true },
  "tencent": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/tencentqq", website: "https://cloud.tencent.com", hasFree: true },
  "theb-ai": { category: "aggregator", serviceKinds: ["llm"], website: "https://theb.ai" },
  "together": { category: "apikey", serviceKinds: ["llm", "image", "embedding"], website: "https://api.together.xyz", hasFree: true },
  "topaz": { category: "image", serviceKinds: ["image"], website: "https://topazlabs.com" },
  "trae": { category: "ide", serviceKinds: ["llm"], website: "https://trae.ai" },
  "udio": { category: "apikey", serviceKinds: ["audio"], website: "https://udio.com" },
  "uncloseai": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
  "upstage": { category: "apikey", serviceKinds: ["llm"], website: "https://upstage.ai" },
  "v0-vercel": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/vercel", website: "https://v0.dev" },
  "v0-web": { category: "cookie", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/vercel", website: "https://v0.dev" },
  "venice": { category: "apikey", serviceKinds: ["llm"], website: "https://venice.ai" },
  "venice-web": { category: "cookie", serviceKinds: ["llm"], website: "https://venice.ai" },
  "veo-ai": { category: "noauth", serviceKinds: ["video"], hasFree: true },
  "vercel-ai-gateway": { category: "aggregator", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/vercel", website: "https://vercel.com" },
  "vertex": { category: "enterprise", serviceKinds: ["llm", "embedding"], iconUrl: "https://cdn.simpleicons.org/googlecloud", website: "https://cloud.google.com/vertex-ai", hasFree: true },
  "vertex-partner": { category: "enterprise", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/googlecloud", website: "https://cloud.google.com/vertex-ai" },
  "vllm": { category: "local", serviceKinds: ["llm"], website: "https://vllm.ai" },
  "volcengine": { category: "apikey", serviceKinds: ["llm"], website: "https://www.volcengine.com" },
  "voyage-ai": { category: "embedding", serviceKinds: ["embedding"], website: "https://voyageai.com", hasFree: true },
  "wandb": { category: "apikey", serviceKinds: ["llm"], website: "https://wandb.ai" },
  "watsonx": { category: "enterprise", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/ibm", website: "https://www.ibm.com/watsonx" },
  "windsurf": { category: "oauth", serviceKinds: ["llm"], website: "https://windsurf.com" },
  "xai": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/x/000", website: "https://console.x.ai" },
  "xiaomi-mimo": { category: "apikey", serviceKinds: ["llm"], iconUrl: "https://cdn.simpleicons.org/xiaomi" },
  "xinference": { category: "local", serviceKinds: ["llm"], website: "https://inference.readthedocs.io" },
  "yi": { category: "apikey", serviceKinds: ["llm"], website: "https://01.ai", hasFree: true },
  "youcom": { category: "search", serviceKinds: ["search"], website: "https://you.com" },
  "zai": { category: "apikey", serviceKinds: ["llm"] },
  "zed": { category: "ide", serviceKinds: ["llm"], website: "https://zed.dev" },
  "zenmux": { category: "apikey", serviceKinds: ["llm"], hasFree: true },
};

export const applyProviderMeta = mutation({
  args: {},
  handler: async (ctx) => {
    const providers = await ctx.db.query("providerConfigs").collect();
    let updated = 0;
    for (const p of providers) {
      const meta = PROVIDER_META[p.provider];
      if (meta) {
        await ctx.db.patch(p._id, {
          category: meta.category,
          serviceKinds: meta.serviceKinds,
          iconUrl: meta.iconUrl ?? undefined,
          website: meta.website ?? undefined,
        });
        updated++;
      }
    }
    return { updated, total: providers.length };
  },
});
