import { mutation } from "./_generated/server";

/**
 * Seed 125 NEW providers not in original OmniRoute import.
 * Run once after initial seed to complete the full 230+ provider list.
 */

interface NewProvider {
  provider: string;
  displayName: string;
  enabled: boolean;
  authType: "api_key" | "oauth" | "cookie" | "free" | "device_code" | "service_account";
  tier: "subscription" | "api_key" | "cheap" | "free";
  baseUrl?: string;
  category: string;
  serviceKinds: string[];
  iconUrl?: string;
  website?: string;
}

const NEW_PROVIDERS: NewProvider[] = [
  {
    provider: "360ai",
    displayName: "360 AI",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "9router",
    displayName: "9router",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "proxy",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "adapta-web",
    displayName: "Adapta.org (Adapta One Web)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://adapta.org",
  },
  {
    provider: "agentrouter",
    displayName: "AgentRouter",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "aggregator",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "alibaba-coding",
    displayName: "Alibaba Coding Plan",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/alibabadotcom",
    website: "https://dashscope.aliyun.com",
  },
  {
    provider: "amazon-q",
    displayName: "Amazon Q",
    enabled: false,
    authType: "oauth",
    tier: "free",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/amazonwebservices",
    website: "https://aws.amazon.com/q/",
  },
  {
    provider: "antigravity",
    displayName: "Antigravity",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "antigravity-cli",
    displayName: "Antigravity CLI",
    enabled: false,
    authType: "oauth",
    tier: "free",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "arcee-ai",
    displayName: "Arcee AI",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://arcee.ai",
  },
  {
    provider: "assemblyai",
    displayName: "AssemblyAI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "audio",
    serviceKinds: ["stt"],
    iconUrl: undefined,
    website: "https://assemblyai.com",
  },
  {
    provider: "aws-polly",
    displayName: "AWS Polly",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "audio",
    serviceKinds: ["tts"],
    iconUrl: "https://cdn.simpleicons.org/amazonwebservices",
    website: "https://aws.amazon.com/polly/",
  },
  {
    provider: "azure-ai",
    displayName: "Azure AI Foundry",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "enterprise",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/microsoftazure",
    website: "https://ai.azure.com",
  },
  {
    provider: "azure-openai",
    displayName: "Azure OpenAI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "enterprise",
    serviceKinds: ["llm", "embedding"],
    iconUrl: "https://cdn.simpleicons.org/microsoftazure",
    website: "https://azure.microsoft.com/products/ai-services/openai-service",
  },
  {
    provider: "black-forest-labs",
    displayName: "Black Forest Labs",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "image",
    serviceKinds: ["image"],
    iconUrl: undefined,
    website: "https://blackforestlabs.ai",
  },
  {
    provider: "blackbox-web",
    displayName: "Blackbox Web (Subscription)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://blackbox.ai",
  },
  {
    provider: "brave-search",
    displayName: "Brave Search",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: "https://cdn.simpleicons.org/brave",
    website: "https://search.brave.com",
  },
  {
    provider: "byteplus",
    displayName: "BytePlus ModelArk",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://www.byteplus.com",
  },
  {
    provider: "cablyai",
    displayName: "CablyAI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "aggregator",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "cartesia",
    displayName: "Cartesia",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "audio",
    serviceKinds: ["tts"],
    iconUrl: undefined,
    website: "https://cartesia.ai",
  },
  {
    provider: "chatgpt-web",
    displayName: "ChatGPT Web (Plus/Pro)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/openai",
    website: "https://chatgpt.com",
  },
  {
    provider: "chipotle",
    displayName: "Chipotle Pepper AI (Free)",
    enabled: false,
    authType: "free",
    tier: "free",
    baseUrl: undefined,
    category: "noauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "clarifai",
    displayName: "Clarifai",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "enterprise",
    serviceKinds: ["llm", "image"],
    iconUrl: undefined,
    website: "https://clarifai.com",
  },
  {
    provider: "claude-code",
    displayName: "Claude Code",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/anthropic",
    website: "https://claude.ai/code",
  },
  {
    provider: "claude-web",
    displayName: "Claude Web",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/anthropic",
    website: "https://claude.ai",
  },
  {
    provider: "cline",
    displayName: "Cline",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://cline.bot",
  },
  {
    provider: "cliproxyapi",
    displayName: "CLIProxyAPI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "proxy",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "codex-cloud",
    displayName: "Codex Cloud",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "cloud_agent",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/openai",
    website: "https://openai.com/codex",
  },
  {
    provider: "comfyui",
    displayName: "ComfyUI",
    enabled: false,
    authType: "free",
    tier: "free",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["image"],
    iconUrl: undefined,
    website: "https://comfyui.com",
  },
  {
    provider: "command-code",
    displayName: "Command Code",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "copilot-web",
    displayName: "Microsoft Copilot Web",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/microsoft",
    website: "https://copilot.microsoft.com",
  },
  {
    provider: "crofai",
    displayName: "CrofAI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "cursor",
    displayName: "Cursor IDE",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "ide",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://cursor.com",
  },
  {
    provider: "datarobot",
    displayName: "DataRobot",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "enterprise",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://datarobot.com",
  },
  {
    provider: "deepgram",
    displayName: "Deepgram",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "audio",
    serviceKinds: ["stt", "tts"],
    iconUrl: undefined,
    website: "https://deepgram.com",
  },
  {
    provider: "deepseek-web",
    displayName: "DeepSeek Web",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/deepseek",
    website: "https://chat.deepseek.com",
  },
  {
    provider: "devin",
    displayName: "Devin",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "cloud_agent",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://devin.ai",
  },
  {
    provider: "devin-cli",
    displayName: "Devin CLI (Official)",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://devin.ai",
  },
  {
    provider: "docker-model",
    displayName: "Docker Model Runner",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/docker",
    website: "https://docker.com",
  },
  {
    provider: "doubao-web",
    displayName: "Doubao Web (ByteDance)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://www.doubao.com",
  },
  {
    provider: "duckduckgo",
    displayName: "DuckDuckGo AI Chat",
    enabled: false,
    authType: "free",
    tier: "free",
    baseUrl: undefined,
    category: "noauth",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/duckduckgo",
    website: "https://duckduckgo.com",
  },
  {
    provider: "elevenlabs",
    displayName: "ElevenLabs",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "audio",
    serviceKinds: ["tts"],
    iconUrl: undefined,
    website: "https://elevenlabs.io",
  },
  {
    provider: "empower",
    displayName: "Empower",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "aggregator",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "exa-search",
    displayName: "Exa Search",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "fetch",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: "https://exa.ai",
  },
  {
    provider: "fal-ai",
    displayName: "Fal.ai",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "image",
    serviceKinds: ["image", "video"],
    iconUrl: undefined,
    website: "https://fal.ai",
  },
  {
    provider: "fenayai",
    displayName: "FenayAI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "aggregator",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "firecrawl",
    displayName: "Firecrawl",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "fetch",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: "https://firecrawl.dev",
  },
  {
    provider: "freeaiapikey",
    displayName: "FreeAIAPIKey",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "freemodel",
    displayName: "FreeModel.dev",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: "https://freemodel.dev/v1",
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://freemodel.dev",
  },
  {
    provider: "gemini-business",
    displayName: "Gemini Business (Enterprise)",
    enabled: false,
    authType: "cookie",
    tier: "free",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/google",
    website: "https://gemini.google.com",
  },
  {
    provider: "gemini-cli",
    displayName: "Gemini CLI",
    enabled: false,
    authType: "oauth",
    tier: "free",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/google",
    website: "https://ai.google.dev/gemini-api/docs/cli",
  },
  {
    provider: "gemini-web",
    displayName: "Gemini Web (Free)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/google",
    website: "https://gemini.google.com",
  },
  {
    provider: "github-copilot",
    displayName: "GitHub Copilot",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/github",
    website: "https://github.com/features/copilot",
  },
  {
    provider: "gitlab",
    displayName: "GitLab Duo PAT",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/gitlab",
    website: "https://about.gitlab.com/gitlab-duo/",
  },
  {
    provider: "gitlab-duo",
    displayName: "GitLab Duo",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/gitlab",
    website: "https://about.gitlab.com/gitlab-duo/",
  },
  {
    provider: "gmi-cloud",
    displayName: "Gitlawb Opengateway (GMI Cloud)",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "gmi-mimo",
    displayName: "Gitlawb Opengateway (MiMo)",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "goapi",
    displayName: "GoAPI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "aggregator",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "google-jules",
    displayName: "Google Jules",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "cloud_agent",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/google",
    website: "https://jules.google.com",
  },
  {
    provider: "google-search",
    displayName: "Google Programmable Search",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: "https://cdn.simpleicons.org/google",
    website: "https://programmablesearchengine.google.com",
  },
  {
    provider: "grok-web",
    displayName: "Grok Web (Subscription)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/x/000",
    website: "https://grok.com",
  },
  {
    provider: "huggingchat",
    displayName: "HuggingChat (Free)",
    enabled: false,
    authType: "cookie",
    tier: "free",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/huggingface",
    website: "https://huggingface.co/chat",
  },
  {
    provider: "inner-ai",
    displayName: "Inner.ai (Subscription)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://inner.ai",
  },
  {
    provider: "inworld",
    displayName: "Inworld",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "audio",
    serviceKinds: ["tts"],
    iconUrl: undefined,
    website: "https://inworld.ai",
  },
  {
    provider: "jina-ai",
    displayName: "Jina AI",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "embedding",
    serviceKinds: ["embedding"],
    iconUrl: undefined,
    website: "https://jina.ai",
  },
  {
    provider: "jina-reader",
    displayName: "Jina Reader",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "fetch",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: "https://jina.ai/reader",
  },
  {
    provider: "kilo-code",
    displayName: "Kilo Code",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "kimi-coding",
    displayName: "Kimi Coding",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "kimi-coding-api",
    displayName: "Kimi Coding (API Key)",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "kimi-web",
    displayName: "Kimi Web (Moonshot AI)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://kimi.moonshot.cn",
  },
  {
    provider: "kiro",
    displayName: "Kiro AI",
    enabled: false,
    authType: "oauth",
    tier: "free",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://kiro.dev",
  },
  {
    provider: "laozhang",
    displayName: "LaoZhang AI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "aggregator",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "lemonade",
    displayName: "Lemonade Server",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "linkup-search",
    displayName: "Linkup Search",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "llama-cpp",
    displayName: "llama.cpp",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://github.com/ggerganov/llama.cpp",
  },
  {
    provider: "llamafile",
    displayName: "Llamafile",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://llamafile.ai",
  },
  {
    provider: "llm7",
    displayName: "LLM7.io",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://llm7.io",
  },
  {
    provider: "lmarena",
    displayName: "LMArena (Free)",
    enabled: false,
    authType: "cookie",
    tier: "free",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://lmarena.ai",
  },
  {
    provider: "lmstudio",
    displayName: "LM Studio",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://lmstudio.ai",
  },
  {
    provider: "minimax-video",
    displayName: "Minimax Coding",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "video",
    serviceKinds: ["video"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "muse-spark",
    displayName: "Muse Spark Web (Meta AI)",
    enabled: false,
    authType: "cookie",
    tier: "free",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/meta",
    website: "https://meta.ai",
  },
  {
    provider: "nomic",
    displayName: "Nomic",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["embedding"],
    iconUrl: undefined,
    website: "https://nomic.ai",
  },
  {
    provider: "nvidia-triton",
    displayName: "NVIDIA Triton",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/nvidia",
    website: "https://developer.nvidia.com/triton-inference-server",
  },
  {
    provider: "oci",
    displayName: "OCI Generative AI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "enterprise",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/oracle",
    website: "https://cloud.oracle.com",
  },
  {
    provider: "old-llm",
    displayName: "The Old LLM (Free)",
    enabled: false,
    authType: "free",
    tier: "free",
    baseUrl: undefined,
    category: "noauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "ollama-search",
    displayName: "Ollama Search",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: "https://ollama.com",
  },
  {
    provider: "oobabooga",
    displayName: "oobabooga",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://github.com/oobabooga/text-generation-webui",
  },
  {
    provider: "openai-codex",
    displayName: "OpenAI Codex",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/openai",
    website: "https://openai.com/codex",
  },
  {
    provider: "opencode-free",
    displayName: "OpenCode Free",
    enabled: false,
    authType: "free",
    tier: "free",
    baseUrl: undefined,
    category: "noauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "opencode-go",
    displayName: "OpenCode Go",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "opencode-zen",
    displayName: "OpenCode Zen",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "perplexity-search",
    displayName: "Perplexity Search",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: "https://cdn.simpleicons.org/perplexity",
    website: "https://perplexity.ai",
  },
  {
    provider: "perplexity-web",
    displayName: "Perplexity Web (Pro/Max)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm", "search"],
    iconUrl: "https://cdn.simpleicons.org/perplexity",
    website: "https://perplexity.ai",
  },
  {
    provider: "phind-web",
    displayName: "Phind (Free)",
    enabled: false,
    authType: "cookie",
    tier: "free",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm", "search"],
    iconUrl: undefined,
    website: "https://phind.com",
  },
  {
    provider: "piapi",
    displayName: "PiAPI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "aggregator",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "playht",
    displayName: "PlayHT",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "audio",
    serviceKinds: ["tts"],
    iconUrl: undefined,
    website: "https://play.ht",
  },
  {
    provider: "poe",
    displayName: "Poe",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "aggregator",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://poe.com",
  },
  {
    provider: "poe-web",
    displayName: "Poe Web (Subscription)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://poe.com",
  },
  {
    provider: "qoder-ai",
    displayName: "Qoder AI",
    enabled: false,
    authType: "oauth",
    tier: "free",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "qwen-code",
    displayName: "Qwen Code",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "qwen-web",
    displayName: "Qwen Web (Free)",
    enabled: false,
    authType: "cookie",
    tier: "free",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://chat.qwen.ai",
  },
  {
    provider: "recraft",
    displayName: "Recraft",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "image",
    serviceKinds: ["image"],
    iconUrl: undefined,
    website: "https://recraft.ai",
  },
  {
    provider: "runway",
    displayName: "Runway",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "video",
    serviceKinds: ["video"],
    iconUrl: undefined,
    website: "https://runwayml.com",
  },
  {
    provider: "sap",
    displayName: "SAP Generative AI Hub",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "enterprise",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/sap",
    website: "https://sap.com",
  },
  {
    provider: "sd-webui",
    displayName: "SD WebUI",
    enabled: false,
    authType: "free",
    tier: "free",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["image"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "searchapi",
    displayName: "SearchAPI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: "https://searchapi.io",
  },
  {
    provider: "searxng",
    displayName: "SearXNG Search",
    enabled: false,
    authType: "free",
    tier: "free",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: "https://searxng.org",
  },
  {
    provider: "serper",
    displayName: "Serper Search",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: "https://serper.dev",
  },
  {
    provider: "stability-ai",
    displayName: "Stability AI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "image",
    serviceKinds: ["image"],
    iconUrl: undefined,
    website: "https://stability.ai",
  },
  {
    provider: "suno",
    displayName: "Suno",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["audio"],
    iconUrl: undefined,
    website: "https://suno.com",
  },
  {
    provider: "t3-chat",
    displayName: "t3.chat (Pro/Free)",
    enabled: false,
    authType: "cookie",
    tier: "free",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://t3.chat",
  },
  {
    provider: "tavily",
    displayName: "Tavily Search",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: "https://tavily.com",
  },
  {
    provider: "theb-ai",
    displayName: "TheB.AI",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "aggregator",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://theb.ai",
  },
  {
    provider: "topaz",
    displayName: "Topaz",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "image",
    serviceKinds: ["image"],
    iconUrl: undefined,
    website: "https://topazlabs.com",
  },
  {
    provider: "trae",
    displayName: "Trae",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "ide",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://trae.ai",
  },
  {
    provider: "v0-web",
    displayName: "v0 Vercel Web (Code Gen)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/vercel",
    website: "https://v0.dev",
  },
  {
    provider: "venice-web",
    displayName: "Venice Web (Privacy)",
    enabled: false,
    authType: "cookie",
    tier: "subscription",
    baseUrl: undefined,
    category: "cookie",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://venice.ai",
  },
  {
    provider: "veo-ai",
    displayName: "Veo AI Free",
    enabled: false,
    authType: "free",
    tier: "free",
    baseUrl: undefined,
    category: "noauth",
    serviceKinds: ["video"],
    iconUrl: undefined,
    website: undefined,
  },
  {
    provider: "vllm",
    displayName: "vLLM",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://vllm.ai",
  },
  {
    provider: "voyage-ai",
    displayName: "Voyage AI",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "embedding",
    serviceKinds: ["embedding"],
    iconUrl: undefined,
    website: "https://voyageai.com",
  },
  {
    provider: "watsonx",
    displayName: "IBM watsonx.ai Gateway",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "enterprise",
    serviceKinds: ["llm"],
    iconUrl: "https://cdn.simpleicons.org/ibm",
    website: "https://www.ibm.com/watsonx",
  },
  {
    provider: "windsurf",
    displayName: "Windsurf (Devin CLI)",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "oauth",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://windsurf.com",
  },
  {
    provider: "xinference",
    displayName: "XInference",
    enabled: false,
    authType: "free",
    tier: "subscription",
    baseUrl: undefined,
    category: "local",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://inference.readthedocs.io",
  },
  {
    provider: "youcom",
    displayName: "You.com Search",
    enabled: false,
    authType: "api_key",
    tier: "api_key",
    baseUrl: undefined,
    category: "search",
    serviceKinds: ["search"],
    iconUrl: undefined,
    website: "https://you.com",
  },
  {
    provider: "zed",
    displayName: "Zed IDE",
    enabled: false,
    authType: "oauth",
    tier: "subscription",
    baseUrl: undefined,
    category: "ide",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: "https://zed.dev",
  },
  {
    provider: "zenmux",
    displayName: "ZenMux",
    enabled: false,
    authType: "api_key",
    tier: "free",
    baseUrl: undefined,
    category: "apikey",
    serviceKinds: ["llm"],
    iconUrl: undefined,
    website: undefined,
  },
];

export const seedNewProviders = mutation({
  args: {},
  handler: async (ctx) => {
    // Get existing providers to avoid duplicates
    const existing = await ctx.db.query("providerConfigs").collect();
    const existingSlugs = new Set(existing.map((p) => p.provider));

    let added = 0;
    for (const p of NEW_PROVIDERS) {
      if (existingSlugs.has(p.provider)) continue;
      await ctx.db.insert("providerConfigs", {
        provider: p.provider,
        displayName: p.displayName,
        enabled: false,
        authType: p.authType,
        tier: p.tier,
        baseUrl: p.baseUrl,
        apiKey: undefined,
        apiSecret: undefined,
        oauthAccessToken: undefined,
        sessionCookie: undefined,
        sessionToken: undefined,
        category: p.category,
        serviceKinds: p.serviceKinds,
        iconUrl: p.iconUrl,
        website: p.website,
        models: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
      });
      added++;
    }
    return { added, skipped: NEW_PROVIDERS.length - added };
  },
});
